version: '3.8'
services:
  db:
    image: postgres:15.2
    container_name: postgres_db
    restart: always
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    environment:
      POSTGRES_DB: cuentos
      POSTGRES_USER: cesar
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"